"""
Runs each numbered query from queries.sql against sample_database.db
and writes the results as a Markdown report (query_results.md).
"""
import sqlite3

conn = sqlite3.connect("sample_database.db")
conn.row_factory = sqlite3.Row
cur = conn.cursor()

queries = [
("Q1. Top 5 customers by total spend (completed orders only)", """
SELECT
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    c.city,
    COUNT(o.order_id)          AS completed_orders,
    ROUND(SUM(o.amount), 2)    AS total_spend,
    ROUND(AVG(o.amount), 2)    AS avg_order_value
FROM customers AS c
JOIN orders AS o
    ON o.customer_id = c.customer_id
WHERE o.status = 'completed'
GROUP BY c.customer_id, c.first_name, c.last_name, c.city
ORDER BY total_spend DESC
LIMIT 5;
"""),
("Q2. Average order value - overall vs completed-only", """
SELECT
    COUNT(*)                                              AS all_orders,
    ROUND(AVG(amount), 2)                                 AS avg_order_value_all,
    ROUND(AVG(CASE WHEN status = 'completed' THEN amount END), 2)
                                                           AS avg_order_value_completed_only
FROM orders;
"""),
("Q3. Average order value per customer + CASE spend tier", """
SELECT
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    COUNT(o.order_id)           AS completed_orders,
    ROUND(SUM(o.amount), 2)     AS total_spend,
    ROUND(AVG(o.amount), 2)     AS avg_order_value,
    CASE
        WHEN SUM(o.amount) >= 1000 THEN 'Gold'
        WHEN SUM(o.amount) >= 500  THEN 'Silver'
        ELSE 'Bronze'
    END AS spend_tier
FROM customers AS c
JOIN orders AS o
    ON o.customer_id = c.customer_id
WHERE o.status = 'completed'
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_spend DESC;
"""),
("Q4. Customers spending ABOVE the average customer spend (subquery)", """
SELECT
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    ROUND(SUM(o.amount), 2) AS total_spend
FROM customers AS c
JOIN orders AS o
    ON o.customer_id = c.customer_id
WHERE o.status = 'completed'
GROUP BY c.customer_id, c.first_name, c.last_name
HAVING SUM(o.amount) > (
    SELECT AVG(customer_total)
    FROM (
        SELECT SUM(amount) AS customer_total
        FROM orders
        WHERE status = 'completed'
        GROUP BY customer_id
    )
)
ORDER BY total_spend DESC;
"""),
("Q5. Order outcome breakdown by city", """
SELECT
    c.city,
    COUNT(*) AS total_orders,
    SUM(CASE WHEN o.status = 'completed' THEN 1 ELSE 0 END) AS completed,
    SUM(CASE WHEN o.status = 'cancelled' THEN 1 ELSE 0 END) AS cancelled,
    SUM(CASE WHEN o.status = 'returned'  THEN 1 ELSE 0 END) AS returned
FROM orders AS o
JOIN customers AS c
    ON c.customer_id = o.customer_id
GROUP BY c.city
ORDER BY total_orders DESC;
""")
]

output = ["# Week 2 SQL Assignment — Query Results\n",
          "Run against `sample_database.db` (generated by `generate_db.py`). "
          "Full query text is in `queries.sql`.\n"]

for title, stmt in queries:
    cur.execute(stmt)
    rows = cur.fetchall()
    cols = [d[0] for d in cur.description]
    output.append(f"## {title}\n")
    output.append("| " + " | ".join(cols) + " |")
    output.append("|" + "|".join(["---"] * len(cols)) + "|")
    for r in rows:
        output.append("| " + " | ".join(str(r[c]) for c in cols) + " |")
    output.append("")

result_text = "\n".join(output)
with open("query_results.md", "w") as f:
    f.write(result_text)

print(result_text)
conn.close()
